name: r_project
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.10
  - pip=21.2.4
  - pytube=12.1.2
  - pandas=1.3.5
  - jupyter=1.0.0
  - matplotlib=3.5.1
  - scikit-learn=1.0.2
  - seaborn=0.11.2
  - dash=2.3.1
  - nltk=3.7
  - statsmodels=0.13.2
  - pip:
      - afinn==0.1